### ISSUE TITLE
Edge driver manager doesn't include latest versions

### ISSUE THREAD

**Issue by SirProdigle** [MarketSquare/webdrivermanager#70]
Edge Chromium installer uses 
https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver?maxresults=1000&comp=list&timeout=60000
as the blob link for downloads, maxresults=1000 stops pre-current version so doesn't allow a latest download. Increasing to 5000 results includes latest on the list.

maxresults needs upping or multiple calls need to be done to paginate to get all available versions

**Comment by Asano30** [comment]
**PROBLEM:**
The root of problem is not in the max results, but in the link. The link for downloading edge chromium webdriver is not up to date. The link contains information up to version 82. 

**SOLUTION:**
It seems the link has changed to https://msedgedriver.azureedge.net. There are all versions of the webdriver. Also the timout parameter does not work as expected, therefor request.get function needs to be updated about timeout parameter in _populate_cache method. These two modifications works for me. Since that I am able to download latest edge chromium webdriver.

**NOTE:** 
Be aware that microsoft releases webdriver with greater version number than is the current Edge browser in advance. Eg. Currently is released Edge browser version 93, but latest released webdriver is 95. So it is necessary the find out installed Edge version first and then call for download webdriver with desired version number.
